apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  volumeMode: FileSystem
  nfs:
    path: /mysql
    server: 172.17.0.2
  mountOptions:
  - hard
  - nfsvers=4.1
